
export const CLICK_SQUARE = 'CLICK_SQUARE';
export type CLICK_SQUARE = typeof CLICK_SQUARE;

export const REMOVE_PENDING_ACTION = 'REMOVE_PENDING_ACTION';
export type REMOVE_PENDING_ACTION = typeof REMOVE_PENDING_ACTION;
