
// UI

export const CLICK_SQUARE = 'CLICK_SQUARE';
export type CLICK_SQUARE = typeof CLICK_SQUARE;

export const CLICK_SUBMIT = 'CLICK_SUBMIT';
export type CLICK_SUBMIT = typeof CLICK_SUBMIT;

export const SELECT_SHIPLIST_SHIP = 'SELECT_SHIPLIST_SHIP';
export type SELECT_SHIPLIST_SHIP = typeof SELECT_SHIPLIST_SHIP;

export const REMOVE_PENDING_ACTION = 'REMOVE_PENDING_ACTION';
export type REMOVE_PENDING_ACTION = typeof REMOVE_PENDING_ACTION;

// Mule

export const LOAD_MULE_STATE = 'LOAD_MULE_STATE';
export type LOAD_MULE_STATE = typeof LOAD_MULE_STATE;

export const LOAD_MULE_STATE_SUCCESS = 'LOAD_MULE_STATE_SUCCESS';
export type LOAD_MULE_STATE_SUCCESS = typeof LOAD_MULE_STATE_SUCCESS;

export const LOAD_MULE_STATE_FAILURE = 'LOAD_MULE_STATE_FAILURE';
export type LOAD_MULE_STATE_FAILURE = typeof LOAD_MULE_STATE_FAILURE;