
// UI

export const CLICK_SQUARE = 'CLICK_SQUARE';
export type CLICK_SQUARE = typeof CLICK_SQUARE;

export const CLICK_SUBMIT = 'CLICK_SUBMIT';
export type CLICK_SUBMIT = typeof CLICK_SUBMIT;

export const SELECT_SHIPLIST_SHIP = 'SELECT_SHIPLIST_SHIP';
export type SELECT_SHIPLIST_SHIP = typeof SELECT_SHIPLIST_SHIP;

export const REMOVE_PENDING_ACTION = 'REMOVE_PENDING_ACTION';
export type REMOVE_PENDING_ACTION = typeof REMOVE_PENDING_ACTION;

// Mule

export const LOAD_MULE_STATE = 'LOAD_MULE_STATE';
export type LOAD_MULE_STATE = typeof LOAD_MULE_STATE;

export const LOAD_MULE_STATE_SUCCESS = 'LOAD_MULE_STATE_SUCCESS';
export type LOAD_MULE_STATE_SUCCESS = typeof LOAD_MULE_STATE_SUCCESS;

export const LOAD_MULE_STATE_FAILURE = 'LOAD_MULE_STATE_FAILURE';
export type LOAD_MULE_STATE_FAILURE = typeof LOAD_MULE_STATE_FAILURE;

export const SET_WINNER = 'SET_WINNER';
export type SET_WINNER = typeof SET_WINNER;

export const SUBMIT_TURN_SUCCESS = 'SUBMIT_TURN_SUCCESS';
export type SUBMIT_TURN_SUCCESS = typeof SUBMIT_TURN_SUCCESS;

export const SUBMIT_TURN_FAILURE = 'SUBMIT_TURN_FAILURE';
export type SUBMIT_TURN_FAILURE = typeof SUBMIT_TURN_FAILURE;

export const LOAD_NEW_TURN = 'LOAD_NEW_TURN';
export type LOAD_NEW_TURN = typeof LOAD_NEW_TURN;
